services:
  app:
    build:
      context: ./backend
      target: developer
    working_dir: /app
    ports:
      - "8080:3030"
    volumes:
      - type: bind
        source: ./backend
        target: /app
      - type: volume
        source: maven-cache
        target: /home/developer/.m2
    user: "1000:1000"
    command: tail -f /dev/null
    environment:
      SPRING_API_KEY: ${SPRING_API_KEY}
      MQTT_BROKER_USERNAME: ${MQTT_BROKER_USERNAME}
      MQTT_BROKER_PASSWORD: ${MQTT_BROKER_PASSWORD}
    env_file:
      - path: ./.env.shared
        required: true
    networks:
      - app-network

volumes:
  maven-cache:

networks:
  app-network:
    name: app-network
    driver: bridge